/* Simulation code for FishRobot.Examples.HydraulicsStep generated by the OpenModelica Compiler OpenModelica 1.27.1. */
#if !defined(FishRobot_Examples_HydraulicsStep__MODEL_H)
#define FishRobot_Examples_HydraulicsStep__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "FishRobot.Examples.HydraulicsStep_functions.h"

#define Modelica_Blocks_Tables_Internal_getNextTimeEvent_index 0
#define Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax_index 1
#define Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin_index 2
#define Modelica_Blocks_Tables_Internal_getTable1DValue_index 3
#define Modelica_Blocks_Tables_Internal_getTimeTableTmax_index 4
#define Modelica_Blocks_Tables_Internal_getTimeTableTmin_index 5
#define Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer2_index 6
#define Modelica_Blocks_Types_ExternalCombiTable1D_constructor_index 7
#define Modelica_Blocks_Types_ExternalCombiTable1D_destructor_index 8
#define Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index 9
#define Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_index 10

extern void FishRobot_Examples_HydraulicsStep_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void FishRobot_Examples_HydraulicsStep_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void FishRobot_Examples_HydraulicsStep_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int FishRobot_Examples_HydraulicsStep_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_checkForAsserts(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int FishRobot_Examples_HydraulicsStep_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* FishRobot_Examples_HydraulicsStep_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* FishRobot_Examples_HydraulicsStep_relationDescription(int i);
extern void FishRobot_Examples_HydraulicsStep_function_initSample(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int FishRobot_Examples_HydraulicsStep_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* FishRobot_Examples_HydraulicsStep_linear_model_frame(void);
extern const char* FishRobot_Examples_HydraulicsStep_linear_model_datarecovery_frame(void);
extern int FishRobot_Examples_HydraulicsStep_mayer(DATA* data, modelica_real** res, short *);
extern int FishRobot_Examples_HydraulicsStep_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int FishRobot_Examples_HydraulicsStep_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int FishRobot_Examples_HydraulicsStep_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int FishRobot_Examples_HydraulicsStep_setInputData(DATA *data, const modelica_boolean file);
extern int FishRobot_Examples_HydraulicsStep_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void FishRobot_Examples_HydraulicsStep_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void FishRobot_Examples_HydraulicsStep_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int FishRobot_Examples_HydraulicsStep_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void FishRobot_Examples_HydraulicsStep_read_simulation_info(SIMULATION_INFO* simulationData);
extern void FishRobot_Examples_HydraulicsStep_read_input_fmu(MODEL_DATA* modelData);
extern void FishRobot_Examples_HydraulicsStep_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int FishRobot_Examples_HydraulicsStep_inputNames(DATA* data, char ** names);
extern int FishRobot_Examples_HydraulicsStep_dataReconciliationInputNames(DATA* data, char ** names);
extern int FishRobot_Examples_HydraulicsStep_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int FishRobot_Examples_HydraulicsStep_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int FishRobot_Examples_HydraulicsStep_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int FishRobot_Examples_HydraulicsStep_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "FishRobot.Examples.HydraulicsStep_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(FishRobot_Examples_HydraulicsStep__MODEL_H) */


