/* Additional record code for FishRobot.Examples.HydraulicsStep generated by the OpenModelica Compiler OpenModelica 1.27.1. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "FishRobot.Examples.HydraulicsStep_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

