# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++ -std=c++17
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS= $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers -Wno-parentheses-equality ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I"/usr/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=FishRobot_Examples_HydraulicsStep -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=2 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas  -lm -lomcgc -lryu -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/leo-morph/Dokumenty/GitHub/fish-sim-v0/FishRobot/Examples"
MAINFILE=FishRobot.Examples.HydraulicsStep.c
MAINOBJ=FishRobot.Examples.HydraulicsStep.o
CFILES=FishRobot.Examples.HydraulicsStep_functions.c FishRobot.Examples.HydraulicsStep_records.c \
FishRobot.Examples.HydraulicsStep_01exo.c FishRobot.Examples.HydraulicsStep_02nls.c FishRobot.Examples.HydraulicsStep_03lsy.c FishRobot.Examples.HydraulicsStep_04set.c FishRobot.Examples.HydraulicsStep_05evt.c FishRobot.Examples.HydraulicsStep_06inz.c FishRobot.Examples.HydraulicsStep_07dly.c \
FishRobot.Examples.HydraulicsStep_08bnd.c FishRobot.Examples.HydraulicsStep_09alg.c FishRobot.Examples.HydraulicsStep_10asr.c FishRobot.Examples.HydraulicsStep_11mix.c FishRobot.Examples.HydraulicsStep_12jac.c FishRobot.Examples.HydraulicsStep_13opt.c FishRobot.Examples.HydraulicsStep_14lnz.c \
FishRobot.Examples.HydraulicsStep_15syn.c FishRobot.Examples.HydraulicsStep_16dae.c FishRobot.Examples.HydraulicsStep_17inl.c FishRobot.Examples.HydraulicsStep_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) FishRobot.Examples.HydraulicsStep.makefile FishRobot.Examples.HydraulicsStep_literals.h FishRobot.Examples.HydraulicsStep_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that FishRobot.Examples.HydraulicsStep_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) FishRobot.Examples.HydraulicsStep_functions.h FishRobot.Examples.HydraulicsStep_literals.h $(OFILES)
	$(CC) -I. -o FishRobot.Examples.HydraulicsStep$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-L/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/usr/bin/../lib/x86_64-linux-gnu/omc" "-L/usr/bin/../lib/" -Wl,-rpath="/usr/bin/../lib/" "-L/home/leo-morph/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/leo-morph/.openmodelica/binaries/Modelica" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/x86_64-linux" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/x86_64-linux" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/linux64" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/linux64" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library" -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) FishRobot.Examples.HydraulicsStep_functions.h FishRobot.Examples.HydraulicsStep_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)  "-L/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/usr/bin/../lib/x86_64-linux-gnu/omc" "-L/usr/bin/../lib/" -Wl,-rpath="/usr/bin/../lib/" "-L/home/leo-morph/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/leo-morph/.openmodelica/binaries/Modelica" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/x86_64-linux" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/x86_64-linux" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/linux64" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/linux64" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library" -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o FishRobot.Examples.HydraulicsStep$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-L/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/usr/bin/../lib/x86_64-linux-gnu/omc" "-L/usr/bin/../lib/" -Wl,-rpath="/usr/bin/../lib/" "-L/home/leo-morph/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/leo-morph/.openmodelica/binaries/Modelica" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/x86_64-linux" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/x86_64-linux" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/linux64" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library/linux64" "-L/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library" -Wl,-rpath="/home/leo-morph/.openmodelica/libraries/Modelica 4.1.0+maint.om/Resources/Library" -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f FishRobot.Examples.HydraulicsStep_records.o $(MAINOBJ)

bundle:
	@tar -cvf FishRobot.Examples.HydraulicsStep_Files.tar $(GENERATEDFILES)