#!/usr/bin/env python3
"""Generates actuation files for CalculiX: pressure in chambers L/R.

Waveform (the pump alternately pressurises the left and right chamber):
    p_L(t) = P0 * r(t) * max(0,  sin(2*pi*f*t))
    p_R(t) = P0 * r(t) * max(0, -sin(2*pi*f*t))
    r(t)   = ramp 0 -> 1 over the first T_RAMP seconds (soft start, without
             a pressure shock that would excite the natural vibrations)
Chamber pressure cannot be negative (underpressure would collapse the
chambers), hence half-waves of the sine in opposite phase.

Writes:
    amplitude.inc – *AMPLITUDE definitions (model data, before *STEP)
    dload.inc     – *DLOAD on the chamber walls (step data, inside *STEP)
With P0 = 0 the files are empty (passive tail).

Usage:
    python tools/make_actuation.py <dir> --p0 PA --freq HZ --t-end S [--t-ramp S]
"""
import argparse
from pathlib import Path

import numpy as np


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir", type=Path)
    ap.add_argument("--p0", type=float, required=True, help="pressure amplitude [Pa]")
    ap.add_argument("--freq", type=float, default=1.0, help="frequency [Hz]")
    ap.add_argument("--t-end", type=float, required=True, help="end time [s]")
    ap.add_argument("--t-ramp", type=float, default=None, help="ramp time [s] (default: 1 period)")
    a = ap.parse_args()
    a.outdir.mkdir(parents=True, exist_ok=True)
    amp, dl = a.outdir / "amplitude.inc", a.outdir / "dload.inc"

    if a.p0 == 0:
        amp.write_text("** Passive tail: no actuation\n")
        dl.write_text("** Passive tail: no chamber pressure\n")
        print("actuation: none (P0 = 0)")
        return

    t_ramp = a.t_ramp if a.t_ramp is not None else 1.0 / a.freq
    # 64 points per period – CalculiX interpolates linearly between points
    t = np.linspace(0.0, a.t_end, int(np.ceil(a.t_end * a.freq * 64)) + 1)
    r = np.clip(t / t_ramp, 0.0, 1.0)
    s = np.sin(2 * np.pi * a.freq * t)
    curves = {"AMP_L": r * np.maximum(0.0, s), "AMP_R": r * np.maximum(0.0, -s)}

    with open(amp, "w") as f:
        f.write(f"** Actuation (generated by tools/make_actuation.py – do not edit)\n")
        f.write(f"** f = {a.freq} Hz, ramp {t_ramp} s; values are a multiplier of P0 (0..1)\n")
        for name, y in curves.items():
            # TIME=TOTAL TIME: time counted from the start of the analysis (not the step)
            f.write(f"*AMPLITUDE, NAME={name}, TIME=TOTAL TIME\n")
            for i in range(0, len(t), 4):
                f.write(", ".join(f"{tt:.6g}, {yy:.6g}" for tt, yy in zip(t[i:i + 4], y[i:i + 4])) + "\n")

    with open(dl, "w") as f:
        f.write("** Chamber pressure: P0 * amplitude(t)\n")
        f.write(f"** P0 = {a.p0:g} Pa   PLACEHOLDER – to be identified from measurements\n")
        f.write("*DLOAD, AMPLITUDE=AMP_L\n")
        f.write(f"SchL, P, {a.p0:g}\n")
        f.write("*DLOAD, AMPLITUDE=AMP_R\n")
        f.write(f"SchR, P, {a.p0:g}\n")
    print(f"actuation: P0 = {a.p0:g} Pa, f = {a.freq} Hz, ramp {t_ramp} s")


if __name__ == "__main__":
    main()
