#!/usr/bin/env python3
"""Generation of the fish meshes (OBJ) and XML scenarios from the parameters in config/default.json.

Usage (from the Stonefish/ directory):
    .venv/bin/python tools/make_meshes.py

What it does:
 1. Creates ellipsoid meshes (an icosphere scaled to the semi-axes):
      *_phy.obj – PHYSICAL: few triangles, because Stonefish computes buoyancy and drag
                  separately for EVERY face (cost ~ number of triangles),
      *_vis.obj – VISUAL: smooth, used only for rendering.
    Each mesh is stored in the frame of its own link (link frame):
    frame origin = joint, X axis forward, Z down (NED, required by Stonefish).
 2. Computes volumes and masses (the same way Stonefish will: mass = density·mesh
    volume) and determines the BALLAST (mass and X position) from two conditions:
      - neutral buoyancy with the VBS at half range,
      - longitudinal trim: centre of mass exactly below the centre of buoyancy.
 3. Fills the templates tools/templates/*.scn.in -> data/scenarios/*.scn
    (@NAME@ fields), because Stonefish only allows defining materials in the main
    scenario file – the densities must go into each of them.
 4. Prints a report: masses, volumes, net buoyancy, CG/CB position.
"""

import argparse
import math
import re
import sys
from pathlib import Path

import numpy as np
import trimesh

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fishcfg import ROOT, load_config  # noqa: E402

MESH_DIR = ROOT / "data" / "meshes"
SCN_DIR = ROOT / "data" / "scenarios"
TPL_DIR = ROOT / "tools" / "templates"


# ---------------------------------------------------------------- meshes

def ellipsoid(semi_axes, center=(0.0, 0.0, 0.0), subdiv=2) -> trimesh.Trimesh:
    """Ellipsoid as a scaled icosphere (triangles of similar size)."""
    m = trimesh.creation.icosphere(subdivisions=subdiv, radius=1.0)
    m.apply_scale(semi_axes)
    m.apply_translation(center)
    assert m.is_watertight and m.is_winding_consistent and m.volume > 0, "mesh must be closed"
    return m


def write_obj(mesh: trimesh.Trimesh, path: Path, comment: str):
    """Writes OBJ in the format Stonefish reads: 'v', 'vn', 'f a//a b//b c//c'.

    Per-vertex normals (averaged) -> smooth shading in the renderer.
    Vertex order within a face: counter-clockwise when viewed
    from outside (normal pointing outwards) – the sign of volume and buoyancy depends on it.
    """
    v = mesh.vertices
    n = mesh.vertex_normals
    lines = [f"# {comment}", f"# {len(mesh.faces)} triangles, volume {mesh.volume * 1e6:.3f} ml",
             "# generated by tools/make_meshes.py - do not edit by hand"]
    lines += [f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in v]
    lines += [f"vn {x:.6f} {y:.6f} {z:.6f}" for x, y, z in n]
    lines += [f"f {a + 1}//{a + 1} {b + 1}//{b + 1} {c + 1}//{c + 1}" for a, b, c in mesh.faces]
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


class Part:
    """One body of the fish: physical mesh + position of its frame relative to the hull."""

    def __init__(self, name, mesh, density, origin_x, buoyant=True, tail=True):
        self.tail = tail              # False = body welded to the head (dorsal fin)
        self.name = name
        self.mesh = mesh              # in the link frame
        self.density = density
        self.origin_x = origin_x      # [m] position of the link frame in the hull frame (straight tail)
        self.buoyant = buoyant

    @property
    def volume(self):
        return self.mesh.volume

    @property
    def mass(self):
        return self.density * self.volume

    @property
    def centroid_z(self):
        return self.mesh.center_mass[2]

    @property
    def centroid_x(self):
        """Centre of volume (= centre of mass at constant density) in the hull frame."""
        return self.origin_x + self.mesh.center_mass[0]


def build_meshes(cfg) -> dict:
    g = cfg["geometry"]
    mat = cfg["materials"]
    vbs = cfg["vbs"]
    sp, sv = g["phys_subdiv"], g["vis_subdiv"]
    MESH_DIR.mkdir(parents=True, exist_ok=True)

    out = {"parts": []}

    # --- hull (head): ellipsoid centre = origin of the base_link frame
    hull = ellipsoid(g["hull_semi_axes"], subdiv=sp)
    hull_vis = ellipsoid(g["hull_semi_axes"], subdiv=sv)
    out["parts"].append(Part("Hull", hull, mat["rho_hull"], 0.0, tail=False))
    head_phy, head_vis = hull, hull_vis
    # The dorsal fin is part of the HEAD MESH (union of bodies), not a separate link:
    # Stonefish 1.5 computes link velocities incorrectly in a branched kinematic tree
    # (README, "Stonefish 1.5 pitfalls"), so the fish chain must be serial.
    if g.get("dorsal_enabled", False):
        dc = tuple(g["dorsal_center"])
        dor = ellipsoid(g["dorsal_semi_axes"], dc, sp)
        dor_out = trimesh.boolean.difference([dor, hull], engine="manifold")   # the part sticking out of the hull
        head_phy = trimesh.boolean.union([hull, dor], engine="manifold")
        head_vis = trimesh.boolean.union([hull_vis, ellipsoid(g["dorsal_semi_axes"], dc, sv)], engine="manifold")
        for m in (dor_out, head_phy, head_vis):
            assert m.is_watertight and m.volume > 0, "mesh union/difference must be closed"
        out["parts"].append(Part("Dorsal", dor_out, mat["rho_tail"], 0.0, tail=False))
    write_obj(head_phy, MESH_DIR / "head_phy.obj", "head (hull + dorsal fin) - physical mesh")
    write_obj(head_vis, MESH_DIR / "head_vis.obj", "head (hull + dorsal fin) - visual mesh")

    # --- tail segments: the frame of link i lies ON joint i, the segment extends towards −X.
    n = g["n_segments"]
    L = g["segment_length"]
    for i in range(n):
        s = 1.0 if n == 1 else 1.0 + (g["taper_last"] - 1.0) * i / (n - 1)   # linear taper
        axes = (L / 2 + g["segment_overlap"], g["segment_ry0"] * s, g["segment_rz0"] * s)
        center = (-L / 2, 0.0, 0.0)
        m = ellipsoid(axes, center, sp)
        write_obj(m, MESH_DIR / f"seg{i + 1}_phy.obj", f"tail segment {i + 1} - physical mesh (frame = joint {i + 1})")
        write_obj(ellipsoid(axes, center, sv), MESH_DIR / f"seg{i + 1}_vis.obj", f"tail segment {i + 1} - visual mesh")
        out["parts"].append(Part(f"Seg{i + 1}", m, mat["rho_tail"], g["tail_attach_x"] - i * L))

    # --- fin: a separate link welded (fixed joint) at the end of the last segment.
    # The leading edge of the fin overlaps the segment end by segment_overlap (as in MuJoCo).
    fx = g["fin_semi_axes"][0]
    fin_center = (-fx + g["segment_overlap"], 0.0, 0.0)
    fin = ellipsoid(g["fin_semi_axes"], fin_center, sp)
    write_obj(fin, MESH_DIR / "fin_phy.obj", "caudal fin - physical mesh (frame = end of the last segment)")
    write_obj(ellipsoid(g["fin_semi_axes"], fin_center, sv), MESH_DIR / "fin_vis.obj", "caudal fin - visual mesh")
    fin_origin_x = g["tail_attach_x"] - n * L
    out["parts"].append(Part("Fin", fin, mat["rho_tail"], fin_origin_x))

    out["fin_center_x"] = fin_center[0]
    # Fin area in side projection (XZ plane) – an ellipse with semi-axes fx, fz.
    out["fin_area"] = math.pi * g["fin_semi_axes"][0] * g["fin_semi_axes"][2]

    # --- VBS: two meshes (empty / full) with a common centre. Stonefish interpolates
    # the water volume and its centre linearly between them.
    def vbs_mesh(volume):
        # ellipsoid with 2:1:1 proportions and the given volume
        a = (volume / (4.0 / 3.0 * math.pi * 0.25)) ** (1.0 / 3.0)
        return ellipsoid((a, a / 2, a / 2), subdiv=sp)

    write_obj(vbs_mesh(vbs["v_min"]), MESH_DIR / "vbs_empty.obj", "VBS - tank empty (minimum volume)")
    write_obj(vbs_mesh(vbs["v_max"]), MESH_DIR / "vbs_full.obj", "VBS - tank full (maximum volume)")

    return out


# ---------------------------------------------------------------- mass balance and ballast

def solve_ballast(cfg, parts) -> dict:
    """Ballast mass and X position from the neutral buoyancy and trim conditions.

    Notation (hull frame, straight tail):
      V   – displaced volume (hull + tail + fin); the ballast is INSIDE
            the hull and does not displace extra water (buoyant="false" in XML),
      V_n – water volume in the VBS at neutral buoyancy = half range.
    (1) Σm + m_bal + ρ·V_n = ρ·V                -> m_bal
    (2) Σ(m·x) + m_bal·x_bal + ρ·V_n·x_vbs = x_CB·(ρ·V)  -> x_bal
    """
    rho = cfg["materials"]["rho_water"]
    vbs = cfg["vbs"]
    mat = cfg["materials"]
    V = sum(p.volume for p in parts)
    x_cb = sum(p.volume * p.centroid_x for p in parts) / V
    V_n = 0.5 * (vbs["v_min"] + vbs["v_max"])
    m_parts = sum(p.mass for p in parts)
    m_bal = rho * V - rho * V_n - m_parts
    if m_bal <= 0:
        raise SystemExit(f"Ballast comes out negative ({m_bal * 1e3:.1f} g): hull too heavy – reduce rho_hull.")
    mx = sum(p.mass * p.centroid_x for p in parts) + rho * V_n * vbs["center"][0]
    x_bal = (x_cb * rho * V - mx) / m_bal
    vol_bal = m_bal / mat["rho_ballast"]
    len_bal = vol_bal / (mat["ballast_width"] * mat["ballast_height"])

    # Does the ballast fit inside the hull? We check the 8 corners of the box.
    a, b, c = cfg["geometry"]["hull_semi_axes"]
    worst = 0.0
    for sx in (-1, 1):
        for sy in (-1, 1):
            for sz in (-1, 1):
                x = x_bal + sx * len_bal / 2
                y = sy * mat["ballast_width"] / 2
                z = mat["ballast_z"] + sz * mat["ballast_height"] / 2
                worst = max(worst, (x / a) ** 2 + (y / b) ** 2 + (z / c) ** 2)
    if worst >= 1.0:
        raise SystemExit(f"Ballast ({len_bal * 100:.1f} cm) sticks out of the hull (max (x/a)²+... = {worst:.2f}) – change the cross-section.")
    out = dict(V=V, x_cb=x_cb, V_n=V_n, m_parts=m_parts, m_bal=m_bal, x_bal=x_bal,
               vol_bal=vol_bal, len_bal=len_bal, fit=worst)
    out.update(head_mass_properties(cfg, [p for p in parts if not p.tail], out))
    return out


def head_mass_properties(cfg, head_parts, bal: dict) -> dict:
    """Mass, centre of mass and principal moments of inertia of the HEAD = hull (+ dorsal fin) + ballast.

    Why not a compound body in XML: in Stonefish 1.5 Compound::getAugmentedInertia()
    returns the bare inertia, without the added mass of water (for a plain "model" body it is
    computed from an equivalent ellipsoid). A head without added moment of inertia
    is kicked sideways by every tail beat. Therefore the head is a plain body from the hull
    mesh (buoyancy, drag and added mass come from it), and the mass, centre of mass and inertia
    including the ballast are given explicitly (<mass>, <inertia>, <cg>) – like CAD data.
    """
    mat = cfg["materials"]
    m_b = bal["m_bal"]
    dims = np.array([bal["len_bal"], mat["ballast_width"], mat["ballast_height"]])
    c_b = np.array([bal["x_bal"], 0.0, mat["ballast_z"]])
    I_b = m_b / 12.0 * np.diag([dims[1] ** 2 + dims[2] ** 2, dims[0] ** 2 + dims[2] ** 2, dims[0] ** 2 + dims[1] ** 2])
    M = sum(p.mass for p in head_parts) + m_b
    cg = (sum(p.mass * p.mesh.center_mass for p in head_parts) + m_b * c_b) / M

    def shift(I, m, c):    # parallel axis (Steiner) theorem for the tensor: I + m·(|d|²·1 − d·dᵀ)
        d = c - cg
        return I + m * (np.dot(d, d) * np.eye(3) - np.outer(d, d))

    # trimesh: moment_inertia computed for density 1 about the mesh centre of mass
    I = shift(I_b, m_b, c_b) + sum(shift(p.mesh.moment_inertia * p.density, p.mass, p.mesh.center_mass) for p in head_parts)
    # Principal axes: ballast offset in X and Z gives non-zero I_xz -> axes slightly rotated about Y.
    w, R = np.linalg.eigh(I)
    # axis order and directions as close as possible to the head axes (x, y, z), right-handed frame
    order = [int(np.argmax(np.abs(R[i, :]))) for i in range(3)]
    R = R[:, order]
    w = w[order]
    for i in range(3):
        if R[i, i] < 0:
            R[:, i] = -R[:, i]
    if np.linalg.det(R) < 0:
        R[:, 2] = -R[:, 2]
    # rpy as in Stonefish: Quaternion(yaw, pitch, roll) = Rz·Ry·Rx
    pitch = -math.asin(max(-1.0, min(1.0, R[2, 0])))
    roll = math.atan2(R[2, 1], R[2, 2])
    yaw = math.atan2(R[1, 0], R[0, 0])
    return dict(head_mass=M, head_cg=cg, head_inertia=w, head_cg_rpy=(roll, pitch, yaw))


def report(cfg, parts, bal):
    rho = cfg["materials"]["rho_water"]
    g = 9.81
    vbs = cfg["vbs"]
    print("Fish bodies (physical meshes):")
    print(f"  {'body':8s} {'mass [g]':>9s} {'V [ml]':>9s} {'ρ [kg/m³]':>10s} {'x_C [mm]':>9s}")
    for p in parts:
        print(f"  {p.name:8s} {p.mass * 1e3:9.1f} {p.volume * 1e6:9.1f} {p.density:10.0f} {p.centroid_x * 1e3:9.1f}")
    print(f"  {'Ballast':8s} {bal['m_bal'] * 1e3:9.1f} {'(0)':>9s} {cfg['materials']['rho_ballast']:10.0f} {bal['x_bal'] * 1e3:9.1f}"
          f"   <- computed: {bal['len_bal'] * 100:.2f} x {cfg['materials']['ballast_width'] * 100:.1f}"
          f" x {cfg['materials']['ballast_height'] * 100:.1f} cm")
    m_dry = bal["m_parts"] + bal["m_bal"]
    print(f"  TOTAL (no water in VBS) {m_dry * 1e3:.1f} g, volume {bal['V'] * 1e6:.1f} ml")
    print("\nBuoyancy (buoyant force − weight), the fish without water in the VBS is slightly POSITIVELY buoyant:")
    for label, Vw in (("VBS empty", vbs["v_min"]), ("VBS neutral", bal["V_n"]), ("VBS full", vbs["v_max"])):
        F = (rho * bal["V"] - m_dry - rho * Vw) * g
        print(f"  {label:14s} {Vw * 1e6:5.1f} ml -> {F:+.4f} N")
    # vertical centre of mass (z, NED: + down) with the VBS neutral
    M = m_dry + rho * bal["V_n"]
    z_cg = (bal["m_bal"] * cfg["materials"]["ballast_z"] + rho * bal["V_n"] * vbs["center"][2]
            + sum(p.mass * p.centroid_z for p in parts)) / M
    z_cb = sum(p.volume * p.centroid_z for p in parts) / bal["V"]
    print(f"\nCB of the whole fish: x = {bal['x_cb'] * 1e3:.2f} mm, z = {z_cb * 1e3:+.2f} mm")
    print(f"CG of the whole fish: x = {bal['x_cb'] * 1e3:.2f} mm (trim), z = {z_cg * 1e3:+.2f} mm "
          f"-> CG {(z_cg - z_cb) * 1e3:.2f} mm BELOW CB (righting moment)")
    print(f"Head (hull + ballast): mass {bal['head_mass'] * 1e3:.1f} g, centre of mass "
          f"({', '.join(f'{c * 1e3:+.2f}' for c in bal['head_cg'])}) mm, "
          f"I = ({', '.join(f'{i * 1e4:.2f}' for i in bal['head_inertia'])}) kg·cm², "
          f"principal axes rotated by {math.degrees(bal['head_cg_rpy'][1]):+.2f}° about Y")
    print(f"Fin: side-projection area S = {cfg['_fin_area'] * 1e4:.1f} cm² (for the lift model in C++)")


# ---------------------------------------------------------------- XML templates


def fill_templates(cfg, bal, meshes):
    g, mat, j, vbs, s = cfg["geometry"], cfg["materials"], cfg["joints"], cfg["vbs"], cfg["sensors"]
    fmt = lambda x: repr(float(x))                                   # full precision
    vec = lambda v: " ".join(fmt(x) for x in v)
    lim = math.radians(j["limit_deg"])
    values = {
        "RHO_WATER": fmt(mat["rho_water"]),
        "RHO_HULL": fmt(mat["rho_hull"]),
        "RHO_TAIL": fmt(mat["rho_tail"]),
        "RHO_BALLAST": fmt(mat["rho_ballast"]),
        "BALLAST_DIMS": vec((bal["len_bal"], mat["ballast_width"], mat["ballast_height"])),
        "BALLAST_XYZ": vec((bal["x_bal"], 0.0, mat["ballast_z"])),
        "BALLAST_MASS_G": f"{bal['m_bal'] * 1e3:.1f}",
        "HULL_MASS_G": f"{meshes['parts'][0].mass * 1e3:.1f}",
        "HEAD_MASS": fmt(bal["head_mass"]),
        "HEAD_INERTIA": vec(bal["head_inertia"]),
        "HEAD_CG_XYZ": vec(bal["head_cg"]),
        "HEAD_CG_RPY": vec(bal["head_cg_rpy"]),
        "TAIL_ATTACH_XYZ": vec((g["tail_attach_x"], 0.0, 0.0)),
        "SEG_JOINT_XYZ": vec((-g["segment_length"], 0.0, 0.0)),
        "JOINT_MIN": fmt(-lim),
        "JOINT_MAX": fmt(lim),
        "JOINT_LIMIT_DEG": f"{j['limit_deg']:g}",
        "JOINT_DAMPING": fmt(j["damping"]),
        "VBS_CENTER": vec(vbs["center"]),
        "VBS_NEUTRAL": fmt(bal["V_n"]),
        "VBS_MIN": fmt(vbs["v_min"]),
        "VBS_MAX": fmt(vbs["v_max"]),
        "P_RATE": fmt(s["pressure_rate"]),
        "P_NOISE": fmt(s["pressure_noise"]),
        "IMU_RATE": fmt(s["imu_rate"]),
        "IMU_NOISE_ANGLE": vec(s["imu_noise_angle"]),
        "IMU_NOISE_GYRO": fmt(s["imu_noise_gyro"]),
        "IMU_YAW_DRIFT": fmt(s["imu_yaw_drift"]),
        "IMU_NOISE_ACC": fmt(s["imu_noise_acc"]),
    }
    SCN_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for tpl in sorted(TPL_DIR.glob("*.scn.in")):
        text = tpl.read_text(encoding="utf-8")
        missing = sorted(set(re.findall(r"@([A-Z0-9_]+)@", text)) - set(values))
        if missing:
            raise SystemExit(f"{tpl.name}: no value for {missing}")
        for k, v in values.items():
            text = text.replace(f"@{k}@", v)
        header = (f"<!-- GENERATED by tools/make_meshes.py from tools/templates/{tpl.name}.\n"
                  f"     Make changes in the template or in config/default.json and run the generator again. -->\n")
        # the <?xml?> declaration must stay on the first line
        first, rest = text.split("\n", 1)
        out = SCN_DIR / tpl.name[:-3]
        out.write_text(first + "\n" + header + rest, encoding="utf-8")
        written.append(out.name)
    return written


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", help="overrides file (merge-patch) for config/default.json")
    args = ap.parse_args()
    cfg = load_config(args.config)
    meshes = build_meshes(cfg)
    cfg["_fin_area"] = meshes["fin_area"]
    bal = solve_ballast(cfg, meshes["parts"])
    report(cfg, meshes["parts"], bal)
    written = fill_templates(cfg, bal, meshes)
    print(f"\nMeshes: {MESH_DIR.relative_to(ROOT)}/  Scenarios: {', '.join(written)}")


if __name__ == "__main__":
    main()
