# CalculiX-preCICE adapter configuration
participants:
    Solid:
        interfaces:
        # nodes of the Nsurface set (CalculiX looks for an NSET named N + "patch")
        - nodes-mesh: Solid-Mesh
          patch: surface
          read-data: [Force]
          write-data: [Displacement]

precice-config-file: ../precice-config.xml
